# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RD2ne8sf-O5pAQH-0no5U9emGwDrq7eV
"""

a=float(input("enter a:3"))
b=float(input("enter b:"))
c=float(input("enter c:"))
x=float(input("enter x:"))
y=a*x*x+b*x+c
print(y)