# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RD2ne8sf-O5pAQH-0no5U9emGwDrq7eV
"""

a=5
b=4
c=6
x=4.5
y=a*x*x+b*x+c
print(y)